import 'dart:typed_data';

import 'package:exlser/domain/value_objects/export_format.dart';

/// File generated by a dataset export use case.
class ExportedFile {
  final String name;
  final String extension;
  final String mimeType;
  final ExportFormat format;
  final Uint8List bytes;

  const ExportedFile({
    required this.name,
    required this.extension,
    required this.mimeType,
    required this.format,
    required this.bytes,
  });

  String get fileName => '$name.$extension';
}
